baseURL = "https://vanillanilla.github.io/My_launchx_blog_Vanillanilla/"
languageCode = "en-us"
title = "Bitácora de Viaje"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquí pon tu twitter 👇
  twitter_handle = "@TimeVanilla"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
